const C: Record<string, string> = {
  ".": "",
  k: "#1a1a1d",
  w: "#fffdf8",
  g: "#5dcf6a",
  d: "#2f7a38",
  n: "#b6f5a8",
  r: "#e85d4c",
  o: "#ff8a3d",
  p: "#ffd7b8",
  y: "#f6d365",
  b: "#6ec6ff",
  u: "#7a5cff",
  s: "#c9c4b8",
  m: "#8b5a2b",
  h: "#f2c6de",
  t: "#3d6b3a"
};

function grid(art: string): string[][] {
  const rows = art.trim().split("\n").map((line) => line.trim());
  const width = Math.max(...rows.map((row) => row.length));
  return rows.map((line) => [...line.padEnd(width, ".")].map((ch) => C[ch] || ""));
}

export const SPRITES = {
  ghost: grid(`
    ....kkkkkk....
    ..kkwwwwwwkk..
    .kwwwwwwwwwwk.
    .kwwkwwwwkwwk.
    kwwwwwwwwwwwwk
    kwwkwwwwwwkwwk
    kwwwwwwwwwwwwk
    kwwwwwwwwwwwwk
    kwwkwwkwwkwwkk
    .kwwkwwkwwkwwk
    ..kk..kk..kk..
  `),
  apple: grid(`
    ......dd......
    .....ddn......
    ....kkkkkk....
    ..kkrrrrrrkk..
    .krrrrrrrrrrk.
    krrwrrrrrrrrrk
    krrrrrrrrrrrrk
    krrrrrrrrrrrrk
    .krrrrrrrrrrk.
    ..kkrrrrrrkk..
    ....kkkkkk....
  `),
  pumpkin: grid(`
    ......dd......
    .....ddd......
    ..kkooooookk..
    .kooooooooook.
    kooooyooooooook
    koooooooooooook
    kooooyoyooooook
    .koooooooooook.
    ..kkoooooookk..
    ....kkkkkk....
  `),
  sprout: grid(`
    ......nn......
    .....nggn.....
    ....ngddgn....
    ...ngdkkdgn...
    ....nddddn....
    .....kmmk.....
    .....kmmk.....
    .....kmmk.....
    ....kkmmkk....
    ...kmmmmmmk...
  `),
  clover: grid(`
    ...gg...gg...
    ..gngg.gngg..
    .gnggggggngg.
    ..gggdkdggg..
    ...ggkdkgg...
    ..gngkdkngg..
    .ggggkdkgggg.
    ..gg.kkk.gg..
    .....kkk.....
    ......kk.....
  `),
  bunny: grid(`
    ..kk....kk...
    .kwwk..kwwk..
    .kwwkkkkwwk..
    kwwwwwwwwwwk.
    kwwkwwwwkwwk.
    kwwwwrrwwwwk.
    .kwwwwwwwwk..
    ..kkkkkkkk...
  `),
  frog: grid(`
    ..kkkkkkkk...
    .kggggggggk..
    kggkwggkwggk.
    kggggggggggk.
    kgggwwwwgggk.
    .kggkkkkggk..
    ..kk....kk...
  `),
  kid: grid(`
    ...kkkkkk....
    ..kppppppk...
    .kpwppwpppk..
    .kppppppppk..
    ..kkppppkk...
    .kbbkkkkbbk..
    kbbbbbbbbbbk.
    kbbkbbbbkbbk.
    .kk.kmmk.kk..
    ....kmmk.....
    ...kkmmkk....
  `),
  clock: grid(`
    ....kkkk....
    ..kkwwwwkk..
    .kwwwwwwwwk.
    kwwkwwwwkwwk
    kwwwwkwwwwwk
    kwwwwwkwwwwk
    kwwwwwwkwwwk
    .kwwwwwwwwk.
    ..kkwwwwkk..
    ....kkkk....
  `),
  key: grid(`
    ..kkyyykk....
    .kyyyyyyyk...
    kykkkkkkyk...
    kyk...kyk....
    .kk...kyk....
    ......kyk....
    .....kyyyk...
    .....kyk.k...
    .....kyyyk...
    ......kkk....
  `),
  repo: grid(`
    ..kkkkkkk....
    .kwwwwwwwk...
    kwwkkkkwwwk..
    kwwwwwwwwwk..
    kwwkkkkwwwk..
    kwwwwwwwwwk..
    kwwkkkkwwwk..
    kwwwwwwwwwk..
    .kwwwwwwwk...
    ..kkkkkkk....
  `),
  link: grid(`
    ....kkk......
    ...kbbbkk....
    ..kbbkkbbk...
    ..kbbk.kbk...
    ...kkkbbbk...
    ...kbbbkkk...
    ..kbk.kbbk...
    ..kbbkkbbk...
    ...kkbbbkk...
    .....kkk.....
  `),
  check: grid(`
    ..........kk.
    .........kdk.
    ........kdnk.
    ..kk...kdnk..
    .kdk..kdnk...
    .kndkkdnk....
    ..knddnk.....
    ...kdnk......
    ....kk.......
  `),
  warn: grid(`
    .....kk......
    ....kyyk.....
    ....kyyk.....
    ...kykkyk....
    ...kywwyk....
    ..kyywwyyk...
    ..kyyyyyyk...
    .kyyykkyyyk..
    .kyyyyyyyyk..
    ..kkkkkkkk...
  `),
  leaf: grid(`
    ........nn...
    ......nnggn..
    ....nngddgn..
    ...ngddkdgn..
    ..ngdkdgggn..
    .ngdkdgggn...
    .ndkdgggn....
    ..kdgggn.....
    ..kdggn......
    ...kkn.......
  `),
  star: grid(`
    ......yy......
    ......yy......
    ...yyyyyyyy...
    ....yyyyyy....
    .....yyyy.....
    ....yyyyyy....
    ...yy.yy.yy...
    ..yy......yy..
  `),
  envelope: grid(`
    .kkkkkkkkkkk.
    kwwwwwwwwwwwk
    kwwkkkkkkkwwk
    kwwwkwwwkwwwk
    kwwwwkwkwwwwk
    kwwwwwkwwwwwk
    kwwwwwwwwwwwk
    .kkkkkkkkkkk.
  `),
  pot: grid(`
    .....ggg.....
    ....gdddg....
    ...ggdkdgg...
    ....gdddg....
    ...kkkkkkk...
    ..kmmmmmmmk..
    ..kmmmwmmmk..
    ...kmmmmmk...
    ....kkkkk....
  `),
  moon: grid(`
    ....kkkk.....
    ..kkyyyykk...
    .kyyyyyyyyk..
    kyyyykkyyyyk.
    kyyyy...kyyk.
    kyyyyk..kyyk.
    .kyyyyyyyyk..
    ..kkyyyykk...
    ....kkkk.....
  `)
};

export type SpriteName = keyof typeof SPRITES;

export function PixelArt({
  name,
  scale = 4,
  className = ""
}: {
  name: SpriteName;
  scale?: number;
  className?: string;
}) {
  const pixels = SPRITES[name];
  const h = pixels.length;
  const w = pixels[0]?.length || 0;
  return (
    <svg
      className={`pixel-art ${className}`}
      width={w * scale}
      height={h * scale}
      viewBox={`0 0 ${w} ${h}`}
      shapeRendering="crispEdges"
      aria-hidden="true"
    >
      {pixels.flatMap((row, y) =>
        row.map((fill, x) =>
          fill ? <rect key={`${x}-${y}`} x={x} y={y} width={1} height={1} fill={fill} /> : null
        )
      )}
    </svg>
  );
}
